//
//  JsonArrayArraysUnitTesting.swift
//  AFoundationUnitTesting
//
//  Created by Ihor Myroniuk on 04.10.2020.
//  Copyright Â© 2020 Ihor Myroniuk. All rights reserved.
//

import XCTest
import Foundation
@testable import AFoundation

class JsonArrayArraysUnitTesting: XCTestCase {
//
//    func testArrayArrays() {
//        let booleans = [JsonArray(), JsonArray(), JsonArray()]
//        var array = JsonArray()
//        for boolean in booleans {
//            array.append(boolean)
//        }
//        
//        do {
//            let arrayBooleans = try array.arrayArrays()
//            
//            XCTAssert(arrayBooleans == booleans, "Object returned unexpected arrayArrays \"\(String(describing: arrayBooleans))\" while arrayArrays \"(\(String(describing: booleans))\" is expected)")
//        } catch {
//            XCTFail("Unexpected error \(error) is thrown")
//        }
//    }
//    
//    func testNotArrayArrays() {
//        let notBooleans: [JsonValue] = [JsonArray(), "string2", JsonArray()]
//        var array = JsonArray()
//        for notBoolean in notBooleans {
//            array.append(notBoolean)
//        }
//        
//        do {
//            let arrayBooleans = try array.arrayArrays()
//            
//            XCTFail("Error \(JsonErrorNotArrayArrays.self) has to be thrown, but arrayArrays \"\(String(describing: arrayBooleans))\" is returned")
//        } catch _ as JsonErrorNotArrayArrays {
//            
//        } catch {
//            XCTFail("Unexpected error \(error.self) is thrown")
//        }
//    }
//    
}


